### ISSUE TITLE
Getting Country Details

### ISSUE THREAD

**Issue by simonv3** [TheTorProject/ooni-api#12]
How do we get details and short blurbs about countries? Is there some API with concise information? 

@hellais mentioned that he had a dump of the CIA factbook, which is as good a source as any.

**Comment by hellais** [comment]
Other places where we could take information to place in the country specific pages are:

* We could take the list of country-code mappings to countries here: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements and scrape the summary of the wikipedia article

* http://data.worldbank.org/data-catalog/world-development-indicators

**Comment by hellais** [comment]
Looks like somebody has already scraped and is scraping the cia-factbook here: https://github.com/factbook/factbook.json

**Comment by hellais** [comment]
I am also a bit torn as to wether or not putting content that could lead the country page being opinionated. Perhaps it makes more sense to just include some relevant statistics of the country and not put geo-political background information on the country.

**Comment by simonv3** [comment]
I'm going to close this because we have a bunch of data already, though I think there will be some renaming necessary. 

It's a bower component here:

https://github.com/simonv3/factbook-country-data
