### ISSUE TITLE
make bar chart scrollable if it's over a certain amount of entries

### ISSUE THREAD

**Issue by simonv3** [TheTorProject/ooni-api#22]

**Comment by simonv3** [comment]
Going with pagination on bar chart views. Ready for review.

**Comment by hellais** [comment]
It looks good. I think it can be improved how it looks visually, but I think for the moment it's good enough.

The only thing is that I believe there is an off-by-one problem with making the "View older" link disappear.

You can see this happening, for example, in the case of greece, when even if you are at the last page the "View older" button is still present.

![screen shot 2016-01-20 at 15 36 46](https://cloud.githubusercontent.com/assets/424620/12451868/ec52dacc-bf8b-11e5-8cfa-dc22bfb737fe.png)

**Comment by simonv3** [comment]
Hmm, maybe it's not <= but < (or vice versa)

**Comment by simonv3** [comment]
Fixed in 8acd8dd
