### ISSUE TITLE
Bar chart get rid of "measurement" and "blocked" labels and leave "blocked" always on. 

### ISSUE THREAD

**Issue by simonv3** [TheTorProject/ooni-api#23]

**Comment by simonv3** [comment]
Hey @hellais, let me know what you think of the bar chart here https://github.com/simonv3/ooni-api/commit/9c209885a6cda098301ed19f50f388aa04a7417f

**Comment by hellais** [comment]
It looks very nice!

Currently for all the countries in question there is no longer the issue of the charts crossing over each other, but I still fear that may happen for countries in the future, so if it's not much work I would like to still have support for scrolling back and forward between old and new measurements.

Also I noticed that for countries where we only have 1 set of anomalous reports the labels are not positioned properly as you can see in the case of Indonesia:

![screen shot 2016-01-19 at 13 55 41](https://cloud.githubusercontent.com/assets/424620/12419162/95ed3092-beb4-11e5-9d79-5ec358066874.png)

**Comment by simonv3** [comment]
There is support for scrolling - in Turkey you can scroll sideways. This is through a scrollbar though (overflow-x: scroll) rather than a button. I can have a look at some sort of visual cue that that is possible. 

I'll inspect what's going on with one country - I thought I had the math done properly :/

**Comment by hellais** [comment]
@simonv3 ah I hadn't noticed that since in my browser the scrollbar is hidden by default. It's also not possible to use it unless I use the "scroll right wheel". I think this is an OSX specific issue.

Also I noticed that the greek charts are being clipped:

![screen shot 2016-01-19 at 17 58 31](https://cloud.githubusercontent.com/assets/424620/12425727/6ff4268a-bed6-11e5-80b4-ec8afccd65dc.png)

**Comment by simonv3** [comment]
Cool, that chart definitely makes it look like there's some issues going on with the alignment. I'll have to explore the math there. 

What do you think of the scrollbar - do you want more of a visual indicator and maybe a "scroll" button as well?

**Comment by hellais** [comment]
I was thinking that if there are too many bars to be shown, then it would only show the most recent ones and you have a button that says something like "Older measurements". When you click on that button it will pop the most recent measurement and push an older one to the back on the queue.

**Comment by simonv3** [comment]
Okay, I've fixed the weird sizing bug and added very basic pagination on the bar graph.
