### ISSUE TITLE
Original Paperframes

### ISSUE THREAD

**Issue by simonv3** [TheTorProject/ooni-api#3]
Hey all! Here are the original paperframes sketched between @bnvk and @hellais 

## 1 Home - Grid
![screen shot 2015-12-01 at 17 40 23](https://cloud.githubusercontent.com/assets/424620/11507527/b71055aa-9854-11e5-8a59-ebfa0e8d006d.png)

Clicking on items here will lead to 3

## 2 Home - Map
![screen shot 2015-12-01 at 17 35 23](https://cloud.githubusercontent.com/assets/424620/11507512/a3bea93e-9854-11e5-8101-77e65af873c9.png)

Clicking on countries will lead to the country details page

## 3 Grid - Details
![screen shot 2015-12-01 at 17 50 16](https://cloud.githubusercontent.com/assets/424620/11507817/140a6b82-9856-11e5-9c07-aec0ab53b0bf.png)

Clicking on view report leads to 4

## 4 Details - Test
![screen shot 2015-12-01 at 17 52 22](https://cloud.githubusercontent.com/assets/424620/11507548/ce8fec0e-9854-11e5-9fe5-db588c123a2c.png)

The inputs are clickable and lead to 3

## 5 Map - Country
![screen shot 2015-12-01 at 17 54 12](https://cloud.githubusercontent.com/assets/424620/11507508/9d253be2-9854-11e5-9ab1-899eebfe4fee.png)

This works similarly to 1

I'm still coming to grips with the actual data that these will present, but the merge that @hellais just made with the data fixtures in it is actually really helpful in that regard.

I'll be spending some time this week creating cleaner mockups. Please definitely give feedback in the meantime!

**Comment by hellais** [comment]
Oh my god, I draw soo badly :dizzy_face:

**Comment by TylerJFisher** [comment]
What are you thinking of displaying in the mockup for the `http_requests` test to highlight differences between the experiment/control groups?

**Comment by hellais** [comment]
@TylerJFisher There should be a rendering of the content from the control HTTP request and experiment HTTP request. I am thinking of using a technique similar to this: http://stackoverflow.com/a/4199540. We could also go for doing the rendering not client side, but that would put probably too much strain on the backend.

**Comment by TylerJFisher** [comment]
I think that it's more important to infer which data people are actually going to care about. I think that in wireframe (5) we'll end up overloading the back-end (and our users) if we always return data on all of the metrics we've collected. 

I don't know about you, but if I want to learn more about censorship, and incidences of network tampering taking place, I'm generally not immediately interested in the non-anomalous control group. 

Personally, I think that we should have a materialized view on the countries page listing the number of anomalous/non-anomalous results for each test group, and then make the non-anomalous tests available by-request (either by pushing a button in the UI, or via an API)

**Comment by simonv3** [comment]
At a higher level I wonder if it makes sense to have a third screen (next to [ world | explorer ]) that is a higher level overview? 

Overview -> See a summary of the tests, some neat widgets if we can get to it, etc. (X amount of tests run, country with the most anomalous results, overview of the tests run, etc).
Explorer -> deep dive into the tests
World -> quick overview of the world and finding other countries (I'm reminded of [ejolt atlast](http://ejatlas.org/))

This was kind of inspired by starting to go through some of the requirements. 

---

A question about the transition from 1 - 3 - 4 in the mockups. Why is 4 broken out to be its own page? That seems like information that could fit into 3 (maybe hidden initially?). I think I'm confusing what the purpose of 4 is. Is the information on page 4 informative to the information on page 3?

**Comment by TylerJFisher** [comment]
In my opinion the relationship between [1] and [5] can be improved in one of two ways since [1] / [5] are (theoretically going to be) displaying the same data:
- Place high-level, country-independent statistics on [1] (e.g. there are 1200 `bridge_reachability` reports, and of `ooni-probes` report test failures), and allow people to use [2] to get to [5] (i.e. drill-down on a per-country basis)
- Place high-level statistics for tests, and countries on the world map page below the map, this makes [2] the origin point for all incoming users, and will let users reach pages {1, 3, 4, 5} in a single link; and add a [`Download`] page instead, allowing people to download metrics for a given time period

I'm more or less throwing ideas back, and forth right now, but I think that we should make [2] a central hub that will let users reach all other pages from it. That way, it's easy, and intuitive to get around.

**Comment by anadahz** [comment]
I find the mockup (5) 'Map - Country' to be a bit confusing. Shouldn't this mockup include only the relevant reports  about the country selected on mockup (2) 'Home - Map' ?
Another very interesting feature (that applies to mockups 1, 5) is the use of a date interval (Date From/To) that will limit the results to a defined (if it's defined) timeframe. This could help users narrow down results based on specific events.

**Comment by hellais** [comment]
@anadahz yes you are correct, I made a mistake in making the mockup, but it's basically what you describe: the same view as (1) except that it includes only the reports specific to that country.

**Comment by hellais** [comment]
Most of what is detailed in this has been implemented as a first iteration. I am going to close this ticket.
